version: "3.8"

services:
  elephant-gun:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - TARGET_USER_ID=${TARGET_USER_ID}
      - BOT_OWNER_ID=${BOT_OWNER_ID}
      - JACK_USER_ID=${JACK_USER_ID}
      - OPENAI_API_URL=${OPENAI_API_URL}
      - OPENAI_IMAGE_API_URL=${OPENAI_IMAGE_API_URL}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEPHANT_FACT_CHANCE=${ELEPHANT_FACT_CHANCE:-1.0}
    restart: unless-stopped
